try {
    let d = 0 
    let a = 3,b = 5
    d = a +
    console.log(d);
}
catch {
    console.log("problem");
}